import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-neutral-300 flex flex-col pt-20 px-6">
      <div className="max-w-3xl mx-auto w-full flex-1 mb-20">
        <Link href="/" className="text-brand-accent hover:text-white transition-colors mb-8 inline-block font-medium">
          &larr; Back to Home
        </Link>
        <h1 className="text-4xl font-extrabold text-white mb-8">Terms & Conditions</h1>
        
        <div className="space-y-6 text-sm leading-relaxed glass-panel p-8 rounded-3xl">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using PromptCoroner, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, please do not use our service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>PromptCoroner provides AI-powered prompt analysis and forensic diagnostics. The insights and rewritten prompts provided by our service are generated by artificial intelligence and are intended for informational purposes only.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Disclaimer of Liability</h2>
            <p>We do not guarantee the success, accuracy, or specific outcomes of using the prompts rewritten by our AI. You are solely responsible for how you use the output. PromptCoroner and its creators shall not be held liable for any damages, losses, or negative consequences resulting from the use of our service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Payments and Subscriptions</h2>
            <p>Payments for the Pro tier are processed securely. Due to the digital nature of the service, all sales are final and non-refundable unless legally required. Subscriptions grant unlimited access as defined in the pricing plan.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
